### ISSUE TITLE
Not working on Vim 8

### ISSUE THREAD

**Issue by oscarmorrison** [mjbrownie/swapit#28]
![image](https://cloud.githubusercontent.com/assets/1651212/21619224/c2d7a170-d1bc-11e6-877f-ce87c2d936af.png)

**Comment by mjbrownie** [comment]
Hi,

It wont be an explicitly vim 8 issue. There must be some other incompatibility

It's working here on an osx brew installed setup (brew install vim --HEAD) 

Perhaps try running your vim with nothing but the plugin. This should work. 

vi -u NONE -c ":set nocompatible" -c ":so .vim/plugged/swapit/plugin/swapit.vim"

(Then Flipping on a "False/True" ) 

if you are still having issues paste the output from the :version command.

**Comment by mjbrownie** [comment]
I'll close this. hope you got it sorted. this should be fine. 

:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  4 2017 09:16:22)

call plug#begin()
Plug 'mjbrownie/swapit'
call plug#end()
